### ISSUE TITLE
Update the template for flutter_bloc 8.0.1 + other suggestions

### ISSUE THREAD

**Issue by jorgesarabia** [QAQyzk/freezed_bloc_extension#5]
First of all I thank you for this great tool that you have created. 

Here I describe some changes that I think may be useful for this extension.

## Description

- A new version of flutter_bloc has been released ([flutter_bloc: ^8.0.1](https://pub.dev/packages/flutter_bloc)) so this plugin is deprecated.
- I think it would be nice to remove the '_bloc' from the created folder name. With some co-workers we usually have the BLoCs in a folder that is already descriptive in itself.
- I have noticed that the arguments when creating a new event are converted to an array, this creates problems if for example you want to pass an argument like Map <String, dynamic> json. I think it should just be plain text.

**Comment by QAQyzk** [comment]
Look great! I will merge the pull request and update the extension now. Thanks for the contribution, very appreciated! :+1:
